### ISSUE TITLE
need to require nativescript-cloud

### ISSUE THREAD

**Issue by ThunderAnimal** [NativeScript/nativescript-cloud#121]
Hey folks,

regarding to the documentation just  `const tns = require("nativescript");` is needed. But then I get the following error:

```
const tns = require("nativescript");

tns.nsCloudAuthenticationService.login()
    .then(userInfo => console.log(userInfo))
    .catch(err => console.error(err));
```
```
TypeError: Cannot read property 'login' of undefined
    at Object.<anonymous> (D:\Entwickl\proDoppikMobile\behaelterMobile\script\custom.js:3:34)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

when I change the code and add `require("nativescript-cloud")` all works fine like these:
```
const tns = require("nativescript");
const tns_cloud = require("nativescript-cloud");


tns.nsCloudAuthenticationService.login()
    .then(userInfo => console.log(userInfo))
    .catch(err => console.error(err));
```

I guess your documentation is wrong or it is my fault?

For me it is logic that _lib/bootstrap.ts_ will only executed once, when the package is require and until it will not used the methods are undefined.

Best Regards,
Martin

**Comment by rosen-vladimirov** [comment]
Hey @ThunderAnimal ,
Thanks a lot for pointing this issue. In order to use the library, you have to install it first (in case it is not installed yet) and use the `loadExtensions` method of CLI. I've created a PR to describe the approach.

May I ask you what is the purpose of trying to load the CLI and nativescript-cloud as a library? Maybe we can help you to reach the required behavior.

**Comment by ThunderAnimal** [comment]
Hey @rosen-vladimirov 

thanks for updating the documentation.
We need the nativescript-cloud library for automatic ios builds in the cloud.

**Comment by rosen-vladimirov** [comment]
@ThunderAnimal , you can spawn CLI commands for cloud builds, I'm wondering for your use case, requirements, applications that you need to build, etc. . I'll be glad to assist you further, so feel free to contact me in case you need any help.
